"""Emit a tree-shaken djangd-framework stylesheet.

Reads the same ``DJANGD_FRAMEWORK`` settings filter used by the component
registry, figures out which SCSS partials are actually needed (based on
the components that survived the filter), and emits a minimal entry
stylesheet that ``@use``-s only those partials.

By default the command prints the path of the entry file; pass
``--compile`` to also shell out to a Sass compiler and write the CSS to
``--output``. The compiler is selected in this order: ``sass`` on PATH
(Dart Sass) — fast, preferred; ``npx sass`` if Node is available;
``pysass`` (libsass) if installed in the current Python environment.

Examples
--------

Print just the entry file (no compile)::

    python manage.py djangd_build_css

Compile to a custom CSS bundle::

    python manage.py djangd_build_css --compile --output build/djangd.css

Override the source dir (default: ``djangd_framework/static/djangd/scss``)::

    python manage.py djangd_build_css --source path/to/scss --compile

You can list which components / partials will be included without
emitting anything via ``--dry-run``.
"""
from __future__ import annotations

import shutil
import subprocess
import tempfile
from pathlib import Path

from django.core.management.base import BaseCommand, CommandError

from djangd_framework.registry import registry

import djangd_framework.components  # noqa: F401  (triggers built-in registration)


SCSS_DEFAULT_SOURCE = (
    Path(__file__).resolve().parents[2] / "static" / "djangd" / "scss"
)


def _required_partials() -> list[str]:
    """Return the unique SCSS partials needed for the currently-registered
    components, in a deterministic order (abstracts/tokens + mixins, base
    reset, then component partials sorted, then default theme)."""
    partials: set[str] = set()
    for name in registry.all():
        cls = registry.get(name)
        for p in getattr(cls, "scss_partials", ()):  # type: ignore[attr-defined]
            partials.add(p)
    return sorted(partials)


def _build_entry(partials: list[str]) -> str:
    lines = [
        "// AUTO-GENERATED by `python manage.py djangd_build_css`.",
        "// Edits here will be overwritten — adjust your DJANGD_FRAMEWORK",
        "// settings instead, then re-run the command.",
        "",
        '@use "abstracts/tokens";',
        '@forward "abstracts/mixins";',
        "",
        '@use "abstracts/mixins" as *;',
        '@use "base/reset";',
        "",
    ]
    for p in partials:
        lines.append(f'@use "components/{p}";')
    lines.extend(["", '@use "themes/default" as *;', ""])
    return "\n".join(lines)


def _select_compiler() -> tuple[str, list[str]] | None:
    """Return (label, argv_prefix) for the best available Sass compiler.

    Each prefix accepts ``<input>`` and ``<output>`` appended on the call
    site. Returns None if no compiler is available.
    """
    if shutil.which("sass"):
        return "dart-sass", ["sass", "--no-source-map", "--style=compressed"]
    if shutil.which("npx"):
        return "npx sass", ["npx", "sass", "--no-source-map", "--style=compressed"]
    try:
        import sass as _libsass  # type: ignore  # noqa: F401
    except ImportError:
        return None
    return "libsass", ["__libsass__"]


def _compile_to_css(entry_path: Path, output_path: Path) -> str:
    compiler = _select_compiler()
    if compiler is None:
        raise CommandError(
            "No Sass compiler found. Install Dart Sass (`brew install sass` "
            "or `npm i -g sass`) or `pip install libsass`."
        )
    label, argv = compiler
    if label == "libsass":
        import sass as _libsass

        css = _libsass.compile(
            filename=str(entry_path),
            output_style="compressed",
        )
        output_path.write_text(css, encoding="utf-8")
        return label
    subprocess.run(
        [*argv, str(entry_path), str(output_path)],
        check=True,
    )
    return label


class Command(BaseCommand):
    help = (
        "Generate a tree-shaken djangd-framework SCSS entry (and optionally "
        "compile it to CSS) based on the components your DJANGD_FRAMEWORK "
        "settings have kept registered."
    )

    def add_arguments(self, parser) -> None:
        parser.add_argument(
            "--source",
            type=Path,
            default=SCSS_DEFAULT_SOURCE,
            help="Path to the djangd SCSS source directory (default: the one "
            "shipped inside the installed package).",
        )
        parser.add_argument(
            "--entry-output",
            type=Path,
            default=None,
            help="Where to write the generated SCSS entry file. Default: a "
            "temp file inside --source so relative @use paths resolve.",
        )
        parser.add_argument(
            "--output",
            "-o",
            type=Path,
            default=Path("djangd.css"),
            help="Compiled CSS output path (only used with --compile).",
        )
        parser.add_argument(
            "--compile",
            action="store_true",
            help="Run a Sass compiler against the generated entry and write "
            "CSS to --output.",
        )
        parser.add_argument(
            "--dry-run",
            action="store_true",
            help="Print which components and partials would be included, "
            "without writing anything.",
        )

    def handle(self, *args, **options) -> None:
        source: Path = options["source"]
        if not source.exists():
            raise CommandError(f"SCSS source dir does not exist: {source}")

        partials = _required_partials()
        component_names = sorted(registry.all())

        if options["dry_run"]:
            self.stdout.write(self.style.NOTICE("Components kept:"))
            for n in component_names:
                cls = registry.get(n)
                self.stdout.write(f"  {n} ({getattr(cls, 'group', 'misc')})")
            self.stdout.write(self.style.NOTICE("\nSCSS partials needed:"))
            for p in partials:
                self.stdout.write(f"  components/_{p}.scss")
            return

        entry_content = _build_entry(partials)
        entry_path: Path
        entry_is_temp = False
        if options["entry_output"] is not None:
            entry_path = options["entry_output"]
            entry_path.parent.mkdir(parents=True, exist_ok=True)
            entry_path.write_text(entry_content, encoding="utf-8")
        else:
            # Write inside source so @use paths resolve naturally.
            fd = tempfile.NamedTemporaryFile(
                mode="w", suffix=".scss", dir=source, delete=False, encoding="utf-8"
            )
            try:
                fd.write(entry_content)
            finally:
                fd.close()
            entry_path = Path(fd.name)
            entry_is_temp = True

        if not (entry_is_temp and options["compile"]):
            self.stdout.write(
                self.style.SUCCESS(
                    f"Wrote entry SCSS ({len(partials)} partials, "
                    f"{len(component_names)} components): {entry_path}"
                )
            )

        if options["compile"]:
            output: Path = options["output"]
            output.parent.mkdir(parents=True, exist_ok=True)
            try:
                label = _compile_to_css(entry_path, output)
            finally:
                if entry_is_temp:
                    entry_path.unlink(missing_ok=True)
            size = output.stat().st_size
            self.stdout.write(
                self.style.SUCCESS(
                    f"Compiled {output} ({size:,} bytes, "
                    f"{len(partials)} partials, {len(component_names)} components) with {label}."
                )
            )
        elif options["entry_output"] is None:
            self.stdout.write(
                "Pass --compile to build CSS, or use the entry file with your "
                "own Sass pipeline."
            )
